### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [yumyuu/git-practice#1]
- 謝謝你良心紀錄了上課心得
- git.md 中放的圖片是想要表達什麼意思？這些圖片應該不是你自己畫的，那記得要附上出處。
- 你有沒有發現你「參考資料」這四個字的字級變得很大？ 
<img width="288" alt="image" src="https://github.com/user-attachments/assets/dfff6118-029d-4dbf-afe2-7067d59abe7c">

原因是你在他的下方加上了 `---` ，試試看調整成比較合理的樣子？   
<img width="863" alt="image" src="https://github.com/user-attachments/assets/04b67e8c-93c3-4d7d-9a17-16f380be77f9">

- 「紀錄在 git repo 操作過程中，.git 檔案夾裡的變化，看看你可以觀察到什麼」這題，所以你到底觀察到了什麼變化？實際、具體的樣子，而不是只有文字描述。 -> 講得直白一點，你要怎麼說服我你真的有去觀察？

**Comment by yumyuu** [comment]
謝謝小賴老師的建議，
非常具體明瞭，
也讓我清楚理解自己不足的部分，
我會去修正並參考其他同學的優秀作品加以學習，
謝謝老師!


azole ***@***.***> 於 2024年9月19日 週四 上午2:43寫道：

**Comment by azole** [comment]
謝謝你的回覆，持續進步，就會愈來愈好，都要給自己機會去成長，這學期就讓我們一起加油吧。

如果沒有其他需要跟我討論的事，這個 issue 可以 close 了。
